- libs/movex/README.md
- libs/movex/src/lib/client/Movex.ts
Fixes #29 
I removed the commented code from `libs/movex/src/lib/client/Movex.ts` to improve readability.
Checks:
Happy Hacktoberfest! :)
> removed commented code

- libs/movex/src/lib/client/init.ts
- libs/movex/src/specs/resources/rockPaperScissors.movex.ts
> refactor: :recycle: fix_Self_Refencing_Absolute_Imports

- libs/movex/src/lib/core-types.ts
- libs/movex/src/lib/tools/dispatch.ts
- libs/movex/src/lib/tools/reducer.ts
- libs/movex/src/lib/tools/resourceFile.ts
- libs/movex/src/lib/util.ts
> Remove Movex State unused type

- libs/movex/src/lib/client/MovexResourceObservable.ts
> Removed commented code from MovexResourceObservable.

- libs/movex-core-util/src/lib/core-util/Logsy.ts
Closes: #18 
The internal extra log methods are now togglable with a option in log config.
> Turn off verbose logging

- libs/movex/src/lib/master/ConnectionToClient.ts
> Refactored ConnectionToClient.ts

- libs/movex/src/lib/master/MovexMasterServer.ts
Clean up the code and also the PR requests
> [libs/movex] Clean up code in MovexMasterServer file

- libs/movex-vue/.babelrc
- libs/movex-vue/.eslintrc.json
- libs/movex-vue/README.md
- libs/movex-vue/jest.config.ts
- libs/movex-vue/package-lock.json
- libs/movex-vue/package.json
- libs/movex-vue/project.json
- libs/movex-vue/src/index.ts
- libs/movex-vue/src/lib/movex-vue.spec.ts
- libs/movex-vue/src/lib/movex-vue.ts
- libs/movex-vue/tsconfig.json
- libs/movex-vue/tsconfig.lib.json
- libs/movex-vue/tsconfig.spec.json
- tsconfig.base.json
Status:
Closes: https://github.com/movesthatmatter/movex/issues/25
> feat(movex-vue): setting up nx library

- libs/movex/src/lib/master/index.ts
This PR should resolve issue #84
> style: remove comment for readability

- libs/movex-service/project.json
Status:
Closes: https://github.com/movesthatmatter/movex/issues/101
> feat(movex-service): Added `nx` runner for `tsc` compiler

- libs/movex-core-util/project.json
Status:
Closes: https://github.com/movesthatmatter/movex/issues/117
> feat(movex-core-util): Added nx-runner for tsc compiler

- package.json
Status:
Closes: https://github.com/movesthatmatter/movex/issues/118
> refactor(npm-command): Added tsc-all-lib command to package.json

- .github/workflows/tsc-compiler.yml
Status:
Closes: https://github.com/movesthatmatter/movex/issues/119
> feat(project): Added tsc-compiler to workflow

- libs/movex-core-util/src/lib/core-util/types.ts
> Fix Linting

- libs/movex/src/lib/client/ConnectionToMasterResource.ts
> refactored ConnectionToMasterResource.ts

- libs/movex-core-util/src/lib/core-util/misc.ts
Status:
Closes: https://github.com/movesthatmatter/movex/issues/128
Fixed linting errors occuring in `misc.tsx` in `libs/movex-core`
> fix(libs/movex-core-util): Fixed linting error in misc.ts

- package.json
- yarn.lock
> Add "[project] Install commitizen as a dev dependency #135"

- libs/movex-core-util/src/lib/core-util/EventEmitter.ts
> Removed unused interface

- libs/movex-core-util/src/lib/core-util/ScketIOEmitter.ts
…l/ScketIOEmitter.ts"
Solved issue https://github.com/movesthatmatter/movex/issues/136 : [movex-core-util] Fix linting in file "libs/movex-core-util/src/lib/core-util/ScketIOEmitter.ts"
https://github.com/movesthatmatter/movex/assets/116814372/e425c853-1831-4270-97c3-ae524780d6e8
> Fix "[movex-core-util] Fix linting in file libs/movex-core-util/src/lib/core-util/ScketIOEmitter.ts #136" 

- package.json
I hope this works. I am now tinkering around to see how movex work. Thanks
> Add "[Project] Add command to serve movex-docs #158"

- libs/movex-core-util/src/lib/core-util/Logsy.ts
Fixed all linting issues of `libs/movex-core-util/src/lib/core-util/Logsy.ts`
Closes - 
[#138](https://github.com/movesthatmatter/movex/issues/138) - Fix linting Errors in File:` Logsy.ts `
> Fixed all linting issues of logsy.ts

- libs/movex/src/lib/client/ConnectionToMaster.ts
Status:
Fixes: https://github.com/movesthatmatter/movex/issues/163
> fix(lint): connection-to-master

- libs/movex/src/lib/master/MovexMasterResource.ts
Status:
Fixes: https://github.com/movesthatmatter/movex/issues/166
> fix(lint): movex-master-resource

- libs/movex/src/lib/movex-store/MemoryMovexStore.spec.ts
Status:
Fixes: https://github.com/movesthatmatter/movex/issues/167
> fix(lint): memory-movex-store-spec

- libs/movex/src/specs/ClientMasterOrchestration/ClientMaster.match.spec.ts
Status:
Fixes: https://github.com/movesthatmatter/movex/issues/168
> fix(lint): client-master-match-spec

- apps/movex-docs/theme.config.tsx
Status:
Fixes: https://github.com/movesthatmatter/movex/issues/178
> movex-docs-desc config update

- libs/movex/src/specs/Movex.spec.ts
Status:
Fixes: https://github.com/movesthatmatter/movex/issues/180
> fix(lint): specs/Movex.spec.ts

- libs/movex/src/specs/MovexMasterResource.spec.ts
Fixes #181
This PR fixes the linting issue in `MovexMasterResource.spec.ts`.
> Fixed linting in 'MovexMasterResource.spec.ts'

- libs/movex/src/lib/io-connection/io-connection.ts
Fixes #164 
This is the PR for fixing the linting issue on `io-connection.ts`, this file is passed. 
P.S. There are a bunch of `lib` files that have linting issues other than these two (issue-164, issue-179). I'd like to fix all of these linting errors on a new issue. Could you please create one linting issue and assign it to me? or I can create an issue by myself. Let me know what you'd like to do. Thanks!
> Fixed linting issue on `io-connection.ts`

- libs/movex/.eslintrc.json
- libs/movex/src/specs/ClientMasterOrchestration/ClientMaster.spec.ts
Fixes #179 
This is the PR for fixing `no-var-requires` linting issue on `ClientMaster.spec.ts` by updating `.eslintrc.json`.
> Fixed linting issue on 'ClientMaster.spec.ts'

- libs/movex-examples/src/modules/counter/reducer.ts
- libs/movex-examples/src/movex.config.ts
- libs/movex-react-local-master/src/lib/MovexLocalProvider.tsx
- libs/movex-react/src/lib/MovexBoundResource.tsx
- libs/movex-react/src/lib/MovexContext.ts
- libs/movex-react/src/lib/MovexProvider.tsx
- libs/movex-react/src/lib/hooks.ts
- libs/movex-react/src/lib/type.ts
- libs/movex/src/lib/MovexBoundResource.ts
- libs/movex/src/lib/ResourceRegistry.ts
- libs/movex/src/lib/init.ts
> Fixes #199 - Multiple ResourceBoundResource don't keep in sync locally
