libs/movex/src/lib/util.ts
Fixes #28 
I renamed `reconciliatePrivateFragments` to `applyMovexStatePatches` in `libs/movex/src/lib/util.ts`.
Checks:
Happy Hacktoberfest :)
=> renamed to applyMovexStatePatches

libs/movex/src/lib/util.ts
=> imported the md5 function instead of the whole object-hash

libs/movex/src/lib/tools/dispatch.ts
Fixed #48 
I removed the method `getReducerApplicator` in `libs/movex/src/lib/tools/dispatch.ts` and checked that there are no references left anywhere.
=> removed method getReducerApplicator

libs/movex-react/src/lib/MovexBoundResource.tsx, libs/movex-react/src/lib/MovexContextStateChange.tsx, libs/movex-react/src/lib/MovexResourceBounder.tsx
Fixes #38 
Hey @GabrielCTroia I'm requesting to review my changes. Please let me know if you have any feedback.
=> Removed self referencing absolute imports [libs/movex-react]

libs/movex/src/specs/MovexClientResourceObservable.spec.ts
Fixes #61 
Hey I removed the `applyAction()` comment in `libs/movex/src/specs/MovexClientResourceObservable.spec.ts`.
Checks:
=> removed applyAction() comment

libs/movex/src/lib/client/MovexResourceObservable.ts
Fixes #60 
I removed the now deprecated function `applyAction()` in `libs/movex/src/lib/client/MovexResourceObservable.ts`.
Checks:
-  [X] No tests fail
=> removed applyAction() function

libs/movex-core-util/src/lib/core-types.ts
The comments described in the problem were removed: #23
=> clean up CoreTypes file of commented code

apps/movex-docs/pages/docs/how.mdx
=> Corrected Typo in the documentation

apps/movex-docs/modules/home/Hero.tsx
Fixex #68  
Removed comments in `apps\movex-docs\modules\home\Hero.tsx`
Checks:
=> Cleaned up HeroText

libs/movex-core-util/src/lib/core-util/Observable.ts, libs/movex/src/lib/client/MovexResourceObservable.ts, libs/movex/src/specs/MovexClientResourceObservable.spec.ts
Also use onUpdate naming instead of onUpdated to be inline with the interface.
Checks:
Issues:
=> refactor: 💡 Implement IObservable for Observable

libs/movex-react/project.json, libs/movex-react/src/lib/hooks.ts
Status:
Closes: https://github.com/movesthatmatter/movex/issues/99, https://github.com/movesthatmatter/movex/issues/103
Both issues being co-related
=> fix: added `nx` runner for `tsx` compiler + property `onUpdated` fixed

libs/movex/project.json
Status:
Closes: https://github.com/movesthatmatter/movex/issues/98
=> fix(lib/movex): Added nx runner for tsc compiler

libs/movex-server/src/bin.ts
Closes: [#130](https://github.com/movesthatmatter/movex/issues/130)
=> Fix linting errors in libs/movex-server

libs/movex-core-util/src/lib/core-util/ResultError.ts
Status:
Closes: https://github.com/movesthatmatter/movex/issues/127
Fixed linting issues occuring in `ResultError.ts` in `libs/movex-core-util`
=> fix(libs/movex-core-util): Fixed linting error in resulterror.ts

libs/movex-core-util/src/lib/core-util/EventEmitter.ts, libs/movex-react/src/lib/MovexProvider.tsx, libs/movex-react/src/lib/hooks.ts, libs/movex-react/src/lib/movex-local/MovexLocalMasterProvider.tsx
=> refactor: 💡 Fix linting errors in libs/movex-react

.github/workflows/test.yml
Done Issue #149 and Issue #150 :
- Renamed the name field from CI to Tests
- Renamed the workflow file name from node.js.yml to test.yml
- Removed the 18.x from the node-versions matrix
=> Fix "[project] Rename the Github Action: node.js.yml #150" and "[project] Remove the node-18.x from CI Github Action #149"

libs/movex-core-util/src/lib/core-util/types.ts
Fixed all linting issues of `libs/movex-core-util/src/lib/core-util/types.ts`
1. Removed `AnyRecord` as it is not used anywhere
2. Changed `object` to a `Record` type
Closes - 
[#140](https://github.com/movesthatmatter/movex/issues/140) - Fix linting Errors in File: `libs/movex-core-util/src/lib/core-util/types.ts`
=> Fixed all linting issues of core-util types.ts

libs/movex-react/src/specs/hooks/useMovex.spec.ts
#104 
- Added `spec` and `hooks` folder to the `movex-react`;
- Added a spec for `useMovex` hook; 
- used `renderHook` from `testing-library/react` to test custom hooks;
> By submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/movesthatmatter/movex/blob/main/CODE_OF_CONDUCT.md)
=> [libs/movex-react] Add spec for useMovex hook

libs/movex-core-util/src/lib/core-types.ts
Status:
Closes: https://github.com/movesthatmatter/movex/issues/126
=> fix(libs/movex-core-util): Added new type of EmptyObject

libs/movex/src/lib/io-connection/io-events.ts
Fixes #165 
This is the simple PR to fix linting in `io-events.ts`.
=> Fixed linting in 'io-events.ts'
